### ISSUE TITLE
how to use on android?

### ISSUE THREAD

**Issue by qyzhaojinxi** [hex11/Naive#1]
I want to set socks proxy on android. So how can I use your NaiveSocksAndroid?

**Comment by hex11** [comment]
Sorry for the late reply.
Did you mean to setup a socks client or server?
Find "Edit configration" in the three-dots menu, and...

Client:
```
[android]
vpn = { Handler: 'socksclient' }

[out.socksclient]
type = 'socks'
connect = 'yourserver.com'
port = 1080
```

And server:
```
[in.socksserver]
type = 'socks'
listen = '0.0.0.0'
port = 1080
out = 'direct'
```

**Comment by qyzhaojinxi** [comment]
Thank you for your reply. I really suggest there is a guide or video to show how to use.
